language: php

php:
  - '7.4snapshot'

services:
  - mysql

before_script:
  - composer install
  - echo -e "DB_HOST=localhost\nDB_USER=root\nTEST_DB_NAME=phpclub_test" > .env
  - mysql -e 'CREATE DATABASE phpclub_test;'
  - APP_ENV=test vendor/bin/doctrine-migrations migrations:migrate --no-interaction

script:
  - composer sa
  - APP_ENV=test vendor/bin/doctrine orm:validate-schema
  - vendor/bin/phpunit --testdox

after_success:
  - openssl aes-256-cbc -K $encrypted_5c05c901a3e7_key -iv $encrypted_5c05c901a3e7_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - BRANCH=$TRAVIS_BRANCH bash bin/deploy.sh

notifications:
  email: false
