<header class="clearfix">
    <nav class="navigation">
        <a class="logo" href="/">phpClub</a>

        <ul>
            <li><a target="_blank" href="http://codedokode.github.io/phpbook">Уроки</a></li>
            <li><a href="/about">О Сайте</a></li>
        </ul>
    </nav>

    <?php if ($logged) : ?>
        <ul class="authorization-menu">
            <li><b><?= $logged->getName() ?></b></li>
            <li><a href="/config/">Настройки</a></li>
            <li>
                <form method="post" name="logout" action="/logout/">
                    <input type="hidden" name="token" value="<?= $_COOKIE['token'] ?>">
                    <input type="submit" value="Выход">
                </form>
            </li>
        </ul>
    <?php endif; ?>

    <form method="get" name="search" class="search-form" action="/search">
        <label>
            <input type="text" name="q" placeholder="Поиск" value="<?= (isset($query)) ? htmlspecialchars($query, ENT_QUOTES) : '' ?>">
        </label>
    </form>
</header>

<div class="clarification">
    «phpClub» — архив тем ("тредов") посвещённых изучению PHP и веб-технологий.<br>
</div>

<?php if (isset($breadcrumbs)) : ?>
    <div class="breadcrumbs">
        <ul>
            <?php foreach ($breadcrumbs as $title => $url): ?>
                <li><a class="breadcrumb" href="<?= \htmlspecialchars($url, ENT_QUOTES, 'UTF-8') ?>"><?= \htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>