<header class="clearfix">
    <nav class="navigation">
        <a class="logo" href="/">phpClub</a>

        <ul>
            <li><a target="_blank" href="http://codedokode.github.io/phpbook">Уроки</a></li>
            <li><a href="/about">О Сайте</a></li>
        </ul>
    </nav>

    <form method="get" name="search" class="search-form" action="/search">
        <label>
            <input type="text" name="q" placeholder="Поиск" value="<?= (isset($query)) ? htmlspecialchars($query, ENT_QUOTES) : '' ?>">
        </label>
    </form>
</header>

<div class="clarification">
    «phpClub» — архив тем ("тредов"), посвящённых изучению PHP и веб-технологий.<br>
</div>

<?php if (isset($breadcrumbs)) : ?>
    <div class="breadcrumbs">
        <ul itemscope itemtype="http://schema.org/BreadcrumbList">
            <?php $i = 0; ?>
            <?php foreach ($breadcrumbs as $title => $url): ?>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <a
                       class="breadcrumb"
                       itemprop="item"
                       href="<?= \htmlspecialchars($url, ENT_QUOTES, 'UTF-8') ?>"
                    >
                        <span itemprop="name">
                            <?= \htmlspecialchars($title, ENT_QUOTES, 'UTF-8') ?>
                        </span>
                    </a>
                    <meta itemprop="position" content="<?= ++$i ?>" />
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>