<!DOCTYPE html>
<html>
    <head>
        <title><?= $title ?? 'phpClub' ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="initial-scale=1">
        <link id="favicon" rel="shortcut icon" href="/media/images/phpClub.ico">
        <link href="/media/fonts/Fira/fira.css" type="text/css" rel="stylesheet">
        <link href="/media/css/font-awesome.css" title="makaba" type="text/css" rel="stylesheet">
        <link href="/media/css/fontawesome-all.min.css" type="text/css" rel="stylesheet">
        <link href="/media/css/pace.css" type="text/css" rel="stylesheet">
        <link href="/media/css/styles.css" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="/media/js/jquery-3.3.1.min.js"></script>
        <script type="text/javascript" src="/media/js/pace.min.js"></script>
        <script type="text/javascript" src="/media/js/ejs.min.js"></script>
        <script type="text/javascript" src="/media/js/script.js"></script>
    </head>

    <body>