    <footer>
        <!-- It suppose be in OP head -->
        <?php if ($logged) : ?>
            <span class="archive-link-form"> 
                <form method="post" name="archive-link" action="/addarchivelink/">
                    <input type="hidden" name="thread" value="<?= $thread->getNumber() ?>" required>
                    Добавить архив: <input type="text" name="archive-link">
                    <input type="submit" name="submit" value="Ок">
                </form>

                <div>
                    Удалить ссылки:
                    <ul>
                        <?php foreach ($thread->getArchiveLinks() as $archiveLink) : ?>
                            <li><a href="/removearchivelink/<?= $archiveLink->getId() ?>"><?= $archiveLink->getLink() ?></a>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </span>
        <?php endif; ?>
    </footer>