<?php include(__DIR__ . '/base/header.phtml') ?>
<?php include(__DIR__ . '/base/boardHeader.phtml') ?>

<?php foreach ($threads as $thread) : ?>
    <section class="posts">
        <form id="posts-form">
            <div id="thread-<?= $thread->getNumber() ?>" class="thread">
                <?php foreach ($thread->getPosts() as $post) :?>
                    <?= $this->fetch('/post.phtml', ['threads' => $threads, 'post' => $post]) ?>
                <?php endforeach; ?>
            </div>
            <hr>
        </form>
    </section>
<?php endforeach ?>

<?php include(__DIR__ . '/base/footer.phtml') ?>
