<?php
/** @var \phpClub\Entity\Thread[] $threads */
require __DIR__ . '/base/header.phtml';
require __DIR__ . '/base/boardHeader.phtml';
?>

<?php foreach ($threads as $thread) : ?>
    <section class="posts">
        <form id="posts-form">
            <div id="thread-<?= $thread->getId() ?>" class="thread">
                <?php foreach ($thread->getPosts() as $post) :?>
                    <?= $this->fetch('/post.phtml', ['threads' => $threads, 'post' => $post]) ?>
                <?php endforeach; ?>
            </div>
            <hr>
        </form>
    </section>
<?php endforeach ?>

<?php require __DIR__ . '/base/footer.phtml' ?>
