<?php
/** @var \phpClub\Entity\Thread[]|\Pagerfanta\Pagerfanta $threads */
/** @var string $pagination */
$title = 'Архив тредов клуба изучающих PHP';
require __DIR__ . '/base/header.phtml';
require __DIR__ . '/base/boardHeader.phtml';
?>

<?php if (count($threads)): ?>

    <?= $pagination ?>

    <div class="threads">
        <hr>

        <?php foreach ($threads as $thread): ?>
                <div class="thread" data-id="<?= $thread->getId() ?>">
                    <?php foreach ($thread->getLastPosts() as $post): ?>
                        <?= $this->fetch('/post.phtml', ['threads' => $threads, 'post' => $post, 'thread' => $thread, 'index' => null]) ?>
                    <?php endforeach; ?>
                </div>
                
                <hr>
        <?php endforeach ?>
    </div>

    <?= $pagination ?>

<?php else: ?>
    
    <h2>В приложении отсутствуют треды.</h2>
    
<?php endif ?>

<?php require __DIR__ . '/base/footer.phtml' ?>
