<?php
/**
 * @var int $postId
 * @var Post[] $posts
 */

use phpClub\Entity\Post;

$title = 'Ответы на пост #' . $postId ?>
<?php include(__DIR__ . '/base/header.phtml') ?>
<?php include(__DIR__ . '/base/boardHeader.phtml') ?>

<section class="posts">
    <form id="posts-form">
        <div class="thread">
            <?php foreach ($posts as $i => $post): ?>
                <?= $this->fetch('/post.phtml', ['post' => $post, 'index' => $i + 1]); ?>
            <?php endforeach; ?>
        </div>
        <hr>
    </form>
</section>

<?php include(__DIR__ . '/base/footer.phtml') ?>
