<section class="posts">
    <form id="posts-form">
            <div id="thread-<?= $thread->number ?>" class="thread">     
                <?php foreach ($posts as $post) :?>                

                    <?php include __DIR__ . '/../templates/post.phtml'; ?>
                    
                <?php endforeach; ?>                 
            </div>
            <hr>
    </form>
</section>