<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
    <head>
        <title>phpClub</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link id="favicon" rel="shortcut icon" href="https://2ch.hk/favicon.ico">
        <meta name="viewport" content="initial-scale=1">
        
        <link href="/css/normalize.css" type="text/css" rel="stylesheet">
        <link href="/css/makaba.css?41" title="makaba" type="text/css" rel="stylesheet">
        <link href="/css/font-awesome.min.css" title="makaba" type="text/css" rel="stylesheet">
       
        
        <!-- <script async="" src="https://www.google-analytics.com/analytics.js"></script> -->
        
        <script type="text/javascript" src="/js/jquery-3.js"></script>

        
        <!-- <script type="text/javascript" src="https://2ch.hk/makaba/templates/js/ads.js"></script> -->
                    
        <script type="text/javascript" src="/js/swag.js"></script>
        
        
        <!--[if lt IE 9]>
        <script type="text/javascript" src="/makaba/templates/js/html5shiv.js"></script>
        <![endif]-->

        
            <script type="text/javascript">
                window.addEventListener("load", loadInitialConfig({
                    thread_num: parseInt("0"),
                    board: "pr",
                    likes: "0",
                    enable_oekaki: "0",
                    enable_subject: "1",
                    max_files_size:  "40960",
                    max_comment: "15000",
                }), false);
            </script> 
        
        <style>.ananimas{cursor:pointer}</style>
    </head>
    
    <body class="makaba  browser-ff pace-done">