<?php include(__DIR__ . '/base/header.phtml') ?>

<header class="mainheader">
    <a class="phpClubLogo" href="/">phpClub</a>
</header>

<div class="container">
    <form method="post" name="login" action="/login/" class="authorization-form">
        <label>
            Email
            <input type="email" name="email" pattern=".+@.+\..+" required value="<?= (isset($post['email'])) ? htmlspecialchars($post['email'], ENT_QUOTES) : '' ?>">
            <span class="form-error">
                    <?= (array_key_exists('email', $errors) ? $errors['email'] : '' ) ?>
                </span>
        </label>

        <label>
            Пароль
            <input type="password" name="password" pattern="(.){6,20}" required>
        </label>

        <input type="submit" name="input" value="Войти">
    </form>
</div>

<?php include(__DIR__ . '/base/footer.phtml') ?>
