<?php include(__DIR__ . '/base/header.phtml') ?>
<?php include(__DIR__ . '/base/boardHeader.phtml') ?>

<section class="posts">
    <form id="posts-form">
        <div class="thread">
            <?php foreach ($posts as $post) :?>
                <?php $this->renderToHtml('post', ['post' => $post]); ?>
            <?php endforeach; ?>
        </div>
        <hr>
    </form>
</section>

<?php include(__DIR__ . '/base/footer.phtml') ?>
