<?php
/** @var \phpClub\Entity\Post[]|\Pagerfanta\Pagerfanta $posts */
/** @var \phpClub\Service\Paginator $paginator */
?>
<?php $title = 'Результаты поиска' ?>
<?php include(__DIR__ . '/base/header.phtml') ?>
<?php include(__DIR__ . '/base/boardHeader.phtml') ?>

<form method="get" name="search" class="result-search-form" action="/search">
    <label>
        <input type="text" name="q" placeholder="Поиск" value="<?= (isset($query)) ? htmlspecialchars($query, ENT_QUOTES) : '' ?>">
    </label>
</form>

<?= $pagination ?>

<div class="results">
    <?php foreach ($posts as $post) :?>
        <?= $this->fetch('/post.phtml', ['post' => $post]); ?>
    <?php endforeach; ?>
</div>

<?= $pagination ?>

<hr>

<?php include(__DIR__ . '/base/footer.phtml') ?>
