<?php
/** @var \phpClub\Entity\Thread $thread */
$title = $thread->getPosts()->first()->getTitle() . ' | Архив';
require __DIR__ . '/base/header.phtml';
require __DIR__ . '/base/boardHeader.phtml';
?>

<div class="thread" data-id="<?= $thread->getId() ?>">
    <?php foreach ($thread->getPosts() as $i => $post): ?>
        <?= $this->fetch('/post.phtml', ['post' => $post, 'thread' => $thread, 'index' => $i + 1]) ?>
    <?php endforeach; ?>
</div>
<hr>

<footer>
    <!-- It suppose be in OP head -->
    <?php if ($logged) : ?>
        <span class="archive-link-form">
                <form method="post" name="archive-link" action="/addarchivelink/">
                    <input type="hidden" name="thread" value="<?= $thread->getId() ?>" required>
                    Добавить архив: <input type="text" name="archive-link">
                    <input type="submit" name="submit" value="Ок">
                </form>

                <div>
                    Удалить ссылки:
                    <ul>
                        <?php foreach ($thread->getArchiveLinks() as $archiveLink) : ?>
                        <li><a href="/removearchivelink/<?= $archiveLink->getId() ?>"><?= $archiveLink->getLink() ?></a>
                            <?php endforeach; ?>
                    </ul>
                </div>
            </span>
    <?php endif; ?>
</footer>

<?php include(__DIR__ . '/base/footer.phtml') ?>
