<section class="posts">
    <form id="posts-form">
            <div id="thread-<?= $thread->number ?>" class="thread">     
                <?php foreach ($posts as $post) :?>                
                    <?php $this->render('templates/board/post.phtml', compact('post')); ?>            
                <?php endforeach; ?>                 
            </div>
            <hr>
    </form>
</section>