        <header>
            <a class="phpClubLogo" href="/">phpClub</a>

            <?php if ($logged) : ?>
                <ul class="authorization-menu">
                    <li><b><?= $logged->getName() ?></b></li>
                    <li><a href="/config/">Настройки</a></li>
                    <li>
                        <form method="post" name="logout" action="/logout/">
                            <input type="hidden" name="token" value="<?= $_COOKIE['token'] ?>">
                            <input type="submit" value="Выход">
                        </form>
                    </li>
                </ul>
            <?php endif; ?>
        </header>
        <hr>